entry-pipeline:
  delay: "100"
  source:
    otlp:
      port: {{ .Values.otlp.port }}
      traces_path: /v1/traces
      unframed_requests: true
      ssl: false
      traces_output_format: otel
  route:
    - traces: 'getEventType() == "TRACE"'
  sink:
    - pipeline:
        name: traces-raw
        routes:
          - traces
traces-raw:
  source:
    pipeline:
      name: entry-pipeline
  buffer:
    bounded_blocking:
      buffer_size: 512
      batch_size: 8
  sink:
    - opensearch:
        hosts: {{.Values.opensearch.hosts}}
        index_type: {{ .Values.opensearch.indexType }}
        template_file: {{ .Values.opensearch.templatePath}}
        index: {{ .Values.opensearch.indexName }}
        username: {{ .Values.opensearch.username }}
        password: {{ .Values.opensearch.password }}
        insecure: {{ .Values.opensearch.insecure }}
    - stdout:
